package `in`.koreatech.koin.domain.constant

const val ERROR_FORGOTPASSWORD_BLANK_ACCOUNT = "ERROR_FORGOTPASSWORD_BLANK_ACCOUNT"

const val ERROR_USERINFO_NICKNAME_VALIDATION_NOT_CHECK = "ERROR_USERINFO_NICKNAME_VALIDATION_NOT_CHECK"
const val ERROR_USERINFO_GENDER_NOT_SET = "ERROR_USERINFO_GENDER_NOT_SET"
const val ERROR_INVALID_STUDENT_ID = "ERROR_INVALID_STUDENT_ID"
const val ERROR_OWNERSHOP_NOT_SET = "ERROR_OWNERSHOP_NOT_SET"