name: Gradle Setup

inputs:
  properties:
    required: true
    description: local.properties secret

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Create local.properties
      shell: bash
      run: echo "${{ inputs.properties }}" | base64 -di > ./local.properties

    - name: Gradle cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make gradlew executable
      shell: bash
      run: chmod +x ./gradlew
