name: "Auto Release Adder"
on:
  pull_request:
    types: [closed]
    branches:
      - production
jobs:
  auto_release_adder:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: production

      - name: Get Version From PR
        id: get_version
        run: kotlinc -script .github/scripts/auto_release_adder.kts "${{ github.event.pull_request.body }}"

      - name: Show Fail Log
        if: ${{ steps.create_release_body.outputs.release_version == 'NO_VERSION' }}
        run: |
          if [ "${{ steps.create_release_body.outputs.release_version }}" == "NO_VERSION" ]; then
           echo "Fail: Could not found the version code "
          fi
          exit 1
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get Latest Release Tag
        id: latest_tag
        run: |
          TAG=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "LATEST_TAG : $TAG"
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Get Commit Date of Latest Tag
        id: tag_date
        run: |
          RELEASE_DATE=$(gh release view "$LATEST_TAG" --json createdAt --jq .createdAt)
          echo "RELEASE_DATE : $RELEASE_DATE"
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Create body
        id: create_body
        env:
          IN_PRODUCTION_PRS: ${{ env.IN_PRODUCTION_PRS }}
        run: |
          # 실제 release note 몸체 데이터
          BODY="내용을 수정해주세요."
          
          # 내용을 OUTPUT에 저장 (해당 BODY 가 최종본)
          echo "BODY : $BODY"
          echo "BODY=$BODY" >> $GITHUB_ENV

      - name: Create Release
        env:
          BODY: ${{ env.BODY }}
        run: |
          tag="${{ steps.get_version.outputs.release_version }}"
          title="$tag"
          body="$BODY"
          echo "Version: $tag"
          echo "Body: $body"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{
              \"tag_name\": \"$tag\",
              \"target_commitish\": \"production\",
              \"name\": \"$title\",
              \"body\": \"$body\",
              \"draft\": false,
              \"prerelease\": false,
              \"generate_release_notes\": false
            }"