name: Lint Checker
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create local.properties
        env:
          PROPERTIES: ${{ secrets.PROPERTIES }}
        run: echo $PROPERTIES | base64 -di > ./local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint Check
        run: ./gradlew ktlintCheck