name: "Pick Reviewer"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pick-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pick reviewer
        id: pick_reviewer
        run: kotlinc -script ./.github/scripts/pick_reviewer.kts "${{ github.event.pull_request.title }}"

      - name: Add Reviewer
        uses: madrapps/add-reviewers@v1
        with:
          reviewers: ${{ steps.pick_reviewer.outputs.reviewer }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Mentor
        if: ${{ steps.pick_reviewer.outputs.mentor }}
        uses: madrapps/add-reviewers@v1
        with:
          reviewers: ${{ steps.pick_reviewer.outputs.mentor }}
          token: ${{ secrets.GITHUB_TOKEN }}
